language: python

python:
  - "2.7"
  - "3.5"

install:
  - pip install coveralls
  
script:
  - coverage run hello.py
  
after_success:
  COVERALLS_REPO_TOKEN=wTPgkvdf9xeQ98gUUKBEFt0jhHFUiLyD2 coveralls
